### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by nicpayne713** [WaylonWalker/markata#41]
# Markata run broke in my GH Actions this morning

```
Run markata build --no-pretty
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/markata", line 33, in <module>
    sys.exit(load_entry_point('markata==0.2.0', 'console_scripts', 'markata')())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/cli/cli.py", line 76, in cli
    m = Markata()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/__init__.py", line 117, in __init__
    self.configure()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/__init__.py", line 102, in wrapper
    result = function(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/__init__.py", line 231, in configure
    self._pm.hook.configure(markata=self)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/plugins/setup_logging.py", line 210, in configure
    setup_log(markata, logging.DEBUG)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/plugins/setup_logging.py", line 111, in setup_log
    path = setup_html_log(markata, level)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/plugins/setup_logging.py", line 180, in setup_html_log
    template = Template(template_file.read_text(), undefined=SilentUndefined)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markata/plugins/default_log_template.html'
Error: Process completed with exit code 1.
```

Is this me geing a dope?

**Comment by nicpayne713** [comment]
Resolved https://github.com/WaylonWalker/markata.git to commit c114a52a085f6b8e05cb85cd31ae4dacbabfe2e9 this commit hash is broken. I removed `@develop` in the build and it passed

**Comment by WaylonWalker** [comment]
> I am installing the `develop` branch in CI... should I plan to pin a version to 0.0.2?

For most people this sounds the safest, your site will always build as you expect if you do that.  For someone who can easily roll back, raise an issue, or DM me, If you could build off of latest that would help make sure that these issues are resolved before it hits folks without those debugging skills.

by latest I mean `pip install markata` right out of pypi, or the  @main branch, they are the same.

**Comment by WaylonWalker** [comment]
> Resolved https://github.com/WaylonWalker/markata.git to commit [c114a52](https://github.com/WaylonWalker/markata/commit/c114a52a085f6b8e05cb85cd31ae4dacbabfe2e9) this commit hash is broken. I removed `@develop` in the build and it passed

I ended up having the same issue on my own build, and had resolved it about the same time you raised the issue ironically enough.  It's a non `.py` file missing from the manifest.

**Comment by nicpayne713** [comment]
Sweet, I'll close the issue and plan to only open with issues on `main`!
